server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  #    defer-datasource-initialization: true
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: ${spring.application.name}

greeting:
  message: Hello, Welcome to the User service

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    me.bbbic.userservice: debug
    org.hibernate.type.descriptor.sql: trace

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0