server:
  port: 0

spring:
  application:
    name: order-service
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%x{traceid:-},%x{spanid:-}]"
  level:
    me.bbbic.orderservice: debug

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus