server:
  port: 0

spring:
  application:
    name: order-service
  jpa:
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  config:
    import: "optional:configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: ${spring.application.name}